apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "25"
spec:
  ingressClassName: nginx
  rules:
    - host: production.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canary2
                port:
                  number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary2
  template:
    metadata:
      labels:
        app: canary2
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          args:
            - "--verbose"
          env:
            - name: WHOAMI_NAME
              value: canary2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: canary2
spec:
  selector:
    app: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
