apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: production
                port:
                  number: 80
    - host: other.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: production
                port:
                  number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          args:
            - "--verbose"
          env:
            - name: WHOAMI_NAME
              value: production
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: production
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
