apiVersion: v1
kind: Service
metadata:
  name: foo-bar
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint1-test
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint2-test
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint3-test
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint4-test
spec:
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
