apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: host-route
spec:
  routes:
    - match: Host(`hello.localhost`) && !PathPrefix(`/internal`)
      kind: Rule
      services:
        - name: whoami
          port: 80
