image:
  registry: docker.io
  repository: traefik/traefik
  tag: v100.0.0
  pullPolicy: Never

providers:
  kubernetesIngressNginx:
    enabled: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.localhost`)
    entryPoints: ["web"]
