image:
  registry: docker.io
  repository: traefik/traefik
  tag: v100.0.0
  pullPolicy: Never

providers:
  # kubernetesIngress:
  #   enabled: false
  kubernetesIngressNginx:
    enabled: true
    # ingressClass: "traefik"
    # controllerClass: "traefik.io/ingress-controller"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.localhost`)
    entryPoints: ["web"]

# logs:
#   general:
#     level: DEBUG
